import type { Metadata } from "next";
import "./globals.css";
import { ChatMessageProvider } from "./context/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg antialiased`}>
        <ChatMessageProvider>
          <div className=" flex flex-col justify-between min-h-screen">
            <div className="mb-auto">{children}</div>
          </div>
        </ChatMessageProvider>
      </body>
    </html>
  );
}
